# Generated by Django 6.1.1 on 2026-09-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_category_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={
                "ordering": ["word"],
                "permissions": [
                    ("view_all_words", "Can view all dictionary words"),
                ],
            },
        ),
    ]
