# Generated by Django 6.1.1 on 2026-10-03 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_word_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['owner', 'word'], name='word_owner_word_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['-created_at'], name='word_created_idx'),
        ),
    ]
