# Generated by Django 6.1.1 on 2026-10-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_word_word_owner_word_idx_word_word_created_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_favorite',
        ),
    ]
