# Generated by Django 6.1.1 on 2026-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('deducted', 'Deducted'), ('unavailable', 'Unavailable')], default='pending', max_length=20),
        ),
    ]
