# Generated by Django 6.1.1 on 2026-10-07 11:37

from django.db import migrations, models


def move_legacy_paid_orders_to_processing(apps, schema_editor):
    Order = apps.get_model("shop", "Order")
    Order.objects.filter(status="paid").update(status="processing")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_fulfillment_status_product_weight_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(
            move_legacy_paid_orders_to_processing,
            migrations.RunPython.noop,
        ),
    ]
