# Generated by Django 6.1.1 on 2026-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_normalize_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digital_file_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, upload_to='digital_products/'),
        ),
    ]
