# Generated by Django 6.1.1 on 2026-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('deducted', 'Deducted'), ('unavailable', 'Unavailable'), ('restored', 'Restored')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
